const core = require("@actions/core");
import got from "got";
import { validateSubscription } from "./subscription";

type CommitEntry = {
    message: string;
};

type ValidationResult = {
    message: string;
    valid: boolean;
};

const COMMIT_TYPE_GROUPS: Record<string, string[]> = {
    feature:       ["feat", "improvement"],
    correction:    ["fix", "revert"],
    quality:       ["refactor", "perf", "style"],
    assurance:     ["test"],
    infrastructure:["build", "ci", "chore"],
    documentation: ["docs"],
    misc:          ["merge", "wip"],
};

const CONVENTIONAL_TYPES: string[] = Object.values(COMMIT_TYPE_GROUPS).flat();

const AUTO_GENERATED_PATTERN = /^(Merge |Revert |Reapply |Initial plan)/;

function matchesAutoGeneratedPattern(msg: string): boolean {
    return AUTO_GENERATED_PATTERN.test(msg);
}

function buildTypePattern(allowedTypes: string[]): RegExp {
    const alternation = allowedTypes.map((t) => t.trim()).join("|");
    return new RegExp(`^[^a-z]*(${alternation})(\\([^)]+\\))?!?:`, "i");
}

export function validateCommitFormat(msg: string, allowedTypes = CONVENTIONAL_TYPES): boolean {
    if (matchesAutoGeneratedPattern(msg)) {
        return true;
    }
    return buildTypePattern(allowedTypes).test(msg);
}

function classifyCommit(commit: CommitEntry, allowedTypes: string[]): ValidationResult {
    return {
        message: commit.message,
        valid: validateCommitFormat(commit.message, allowedTypes),
    };
}

function auditCommits(commits: CommitEntry[], allowedTypes: string[]): ValidationResult[] {
    return commits.map((commit) => classifyCommit(commit, allowedTypes));
}

function buildApiHeaders(token: string): Record<string, string> {
    return {
        Accept: "application/vnd.github+json",
        ...(token ? { Authorization: `token ${token}` } : {}),
    };
}

async function fetchCommitsFromApi(
    url: string,
    headers: Record<string, string>
): Promise<CommitEntry[]> {
    try {
        const { body } = await got.get(url, {
            responseType: "json",
            headers,
        });
        if (Array.isArray(body)) {
            return body.map((item: any) => item.commit as CommitEntry);
        }
        return [];
    } catch (error: any) {
        if (error?.response?.statusCode) {
            throw new Error(
                `GitHub API responded with status ${error.response.statusCode}. ` +
                `Verify that GITHUB_TOKEN has the required permissions.`
            );
        }
        core.warning(`Unable to reach GitHub API: ${error?.message ?? String(error)}. Skipping commit validation.`);
        return [];
    }
}

async function resolveCommits(ctx: any, token: string): Promise<CommitEntry[]> {
    const pushCommits = ctx?.payload?.commits;
    if (Array.isArray(pushCommits)) {
        return pushCommits as CommitEntry[];
    }

    const prCommitsUrl = ctx?.payload?.pull_request?.commits_url;
    if (prCommitsUrl) {
        return fetchCommitsFromApi(prCommitsUrl, buildApiHeaders(token));
    }

    return [];
}

function reportResults(results: ValidationResult[]): boolean {
    return results.reduce<boolean>((hasViolation, result) => {
        if (result.valid) {
            core.info(`✅ ${result.message}`);
        } else {
            core.info(`❌ ${result.message}`);
        }
        return hasViolation || !result.valid;
    }, false);
}

async function executeAction(): Promise<void> {
  try {
    await _executeAction();
  } catch (error: any) {
    core.setFailed(error?.message ?? String(error));
  }
}

async function _executeAction(): Promise<void> {
    const { context } = require("@actions/github");
    await validateSubscription()
    core.info("Checking commit messages against the Conventional Commits specification...");

    const token = core.getInput("GITHUB_TOKEN");
    const commits = await resolveCommits(context, token);

    if (commits.length === 0) {
        core.info("No commits found to validate. Skipping.");
        return;
    }

    const allowedTypes = core
        .getInput("allowed-commit-types")
        .split(",")
        .map((t: string) => t.trim());

    core.startGroup("Commit validation results:");
    const results = auditCommits(commits, allowedTypes);
    const hasViolations = reportResults(results);
    core.endGroup();

    if (hasViolations) {
        core.setFailed(
            "One or more commit messages do not follow the Conventional Commits specification."
        );
    } else {
        core.info("All commit messages are valid and follow the Conventional Commits specification.");
    }
}

if (process.env.NODE_ENV !== "test") {
    executeAction();
}
